### ISSUE TITLE
@IntegerType field serialization byte array is correct?

### ISSUE THREAD

**Issue by scmp99** [indunet/fastproto#93]
import org.indunet.fastproto.FastProto;
import org.indunet.fastproto.annotation.type.IntegerType;
import java.nio.ByteBuffer;
import java.util.Arrays;

public class FastProtoTest {
  @IntegerType(0)
  private int nameLen = 5;

  public static void main(String[] args) {
    // Output results:  [5, 0, 0, 0]
    System.out.println(Arrays.toString(FastProto.toByteArray(new FastProtoTest())));
    // toByteArray and parseFrom is right.
    System.out.println(
        FastProto.parseFrom(FastProto.toByteArray(new FastProtoTest()), FastProtoTest.class)
            .nameLen);
    // Output results:  [0, 0, 0, 5]
    System.out.println(Arrays.toString(ByteBuffer.allocate(4).putInt(5).array()));
  }
}

**Comment by Deng-Ran** [comment]
FastProto uses little endian by default, but ByteBuffer uses big endian.
If you want to use big endian, there are two ways.

1. All fields are big endian
```java
    import org.indunet.fastproto.annotation.Endian;
    
    @Endian(EndianPolicy.BIG)
    public class FastProtoTest {
    ...
    }
```

2. Only field value is big endian.
```java
import org.indunet.fastproto.annotation.Endian;

public class FastProtoTest {
  @Endian(EndianPolicy.BIG)
  int value = 5;
}
```

**Comment by Deng-Ran** [comment]
Thanks for your attention.
FastProto is undergoing a major version change, version 4.0 will ensure simple api, clearer data types, and higher  efficiency.

**Comment by scmp99** [comment]
Thanks for the reply. Got it.
